[package]
name = "mdr"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.16.1"

# Enable optimizations for dependencies (incl. Bevy), but not for our code
[profile.dev.package."*"]
opt-level = 3

# Enable high optimizations for release builds
[profile.release]
opt-level = 3
lto = "thin"
